version: '3.8'

services:
  app:
    build: .
    container_name: node_backend
    env_file:
      - .env
    ports:
      - "10000:10000"
    depends_on:
      - redis
    restart: unless-stopped
    # You can define environment variables here or just use .env
    # environment:
    #   - NODE_ENV=production

volumes:
  postgres_data:  